// Command generate-plugins validates pinned packages and generates the offline catalog.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/kumbuka-me/sdk/pluginpackage"
)

const catalogHeader = `// Code generated by scripts/generate-plugins; DO NOT EDIT.

package plugins

import "github.com/kumbuka-me/kumbuka/pkg/plugin"

var catalog = []plugin.BuiltinPackage{
`

type pluginLockEntry struct {
	name    string
	version string
}

// main generates or verifies the first-party plugin catalog.
func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "verify generated content without changing it")
	flag.Parse()
	if err := generate(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// generate renders the plugin catalog source from the pinned plugin lock file.
func generate(root string, check bool) error {
	lock, err := os.ReadFile(filepath.Join(root, "plugins.lock"))
	if err != nil {
		return fmt.Errorf("read plugin lock: %w", err)
	}
	entries, err := parsePluginLock(lock)
	if err != nil {
		return err
	}

	var out bytes.Buffer
	out.WriteString(catalogHeader)
	seen := make(map[string]bool)
	for _, entry := range entries {
		pkg, archiveName, err := readBuiltinPackage(root, entry)
		if err != nil {
			return err
		}
		manifest := pkg.Manifest()
		if manifest.ID != "me.kumbuka."+entry.name || manifest.Version != entry.version || seen[manifest.ID] {
			return fmt.Errorf("package %s does not match unique lock entry", entry.name)
		}
		seen[manifest.ID] = true
		writeBuiltinPackage(&out, manifest.ID, manifest.Version, pkg.Digest(), archiveName)
	}
	out.WriteString("}\n")
	source, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	return writeCatalog(filepath.Join(root, "plugins/catalog_gen.go"), source, check)
}

// parsePluginLock parses non-comment package entries from plugins.lock.
func parsePluginLock(lock []byte) ([]pluginLockEntry, error) {
	var entries []pluginLockEntry
	for line := range strings.SplitSeq(string(lock), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name, version, ok := strings.Cut(line, "=")
		if !ok || name == "" || version == "" {
			return nil, fmt.Errorf("invalid lock entry %q", line)
		}
		entries = append(entries, pluginLockEntry{name: name, version: version})
	}
	return entries, nil
}

// readBuiltinPackage loads the archive pinned by one plugin lock entry.
func readBuiltinPackage(root string, entry pluginLockEntry) (*pluginpackage.Package, string, error) {
	archiveName := entry.name + ".kumbukaplugin"
	data, err := os.ReadFile(filepath.Join(root, "plugins", archiveName))
	if err != nil {
		return nil, "", fmt.Errorf("read plugin package %s: %w", entry.name, err)
	}
	pkg, err := pluginpackage.Read(data)
	if err != nil {
		return nil, "", fmt.Errorf("read plugin package %s: %w", entry.name, err)
	}
	return pkg, archiveName, nil
}

// writeCatalog verifies or writes generated catalog source.
func writeCatalog(path string, source []byte, check bool) error {
	if check {
		current, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated catalog: %w", err)
		}
		if !bytes.Equal(current, source) {
			return fmt.Errorf("%s is stale; run make generate", path)
		}
		return nil
	}
	return os.WriteFile(path, source, 0o644)
}

// writeBuiltinPackage emits one readable generated catalog entry.
func writeBuiltinPackage(out *bytes.Buffer, id, version string, digest [32]byte, archiveName string) {
	fmt.Fprintf(out, "{\nID: %q,\nVersion: %q,\nDigest: [32]byte{\n", id, version)
	for offset := 0; offset < len(digest); offset += 8 {
		for _, value := range digest[offset : offset+8] {
			fmt.Fprintf(out, "0x%02x, ", value)
		}
		out.WriteByte('\n')
	}
	fmt.Fprintf(out, "},\nArchiveName: %q,\n},\n", archiveName)
}
