// Command generate-plugins validates pinned packages and generates the offline catalog.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/kumbuka-me/sdk/pluginpackage"
)

// main generates or verifies the first-party plugin catalog.
func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "verify generated content without changing it")
	flag.Parse()
	if err := generate(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// generate renders the plugin catalog source from the pinned plugin lock file.
func generate(root string, check bool) error {
	lock, err := os.ReadFile(filepath.Join(root, "plugins.lock"))
	if err != nil {
		return err
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by scripts/generate-plugins; DO NOT EDIT.\npackage plugins\nimport \"github.com/kumbuka-me/kumbuka/pkg/plugin\"\nvar catalog = []plugin.BuiltinPackage{\n")
	seen := make(map[string]bool)
	for line := range strings.SplitSeq(string(lock), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name, version, ok := strings.Cut(line, "=")
		if !ok {
			return fmt.Errorf("invalid lock entry %q", line)
		}
		archiveName := name + ".kumbukaplugin"
		data, err := os.ReadFile(filepath.Join(root, "plugins", archiveName))
		if err != nil {
			return err
		}
		pkg, err := pluginpackage.Read(data)
		if err != nil {
			return err
		}
		manifest := pkg.Manifest()
		if manifest.ID != "me.kumbuka."+name || manifest.Version != version || seen[manifest.ID] {
			return fmt.Errorf("package %s does not match unique lock entry", name)
		}
		seen[manifest.ID] = true
		fmt.Fprintf(&out, "{ID:%q, Version:%q, Digest:%#v, ArchiveName:%q},\n", manifest.ID, manifest.Version, pkg.Digest(), archiveName)
	}
	out.WriteString("}\n")
	source, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	path := filepath.Join(root, "plugins/catalog_gen.go")
	if check {
		current, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Equal(current, source) {
			return fmt.Errorf("%s is stale; run make generate", path)
		}
		return nil
	}
	return os.WriteFile(path, source, 0644)
}
