// Command generate-icons creates Kumbuka's Lucide icon picker catalog.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

const (
	lucideModule = "github.com/kaugesaar/lucide-go"
	lucideSource = "icons.go"
	outputFile   = "catalog_gen.go"

	catalogHeader = `// Code generated by go generate; DO NOT EDIT.

package icons

var lucideOptions = []Option{
`
)

var registration = regexp.MustCompile(`registerIcon\("([^"]+)"`)

// moduleMetadata contains the module fields needed from go mod download.
type moduleMetadata struct {
	// Dir stores the dir value used by module metadata.
	Dir string
	// Error stores the error value used by module metadata.
	Error string
}

// main generates the Lucide icon catalog.
func main() {
	if err := run(); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// run locates Lucide, generates the catalog, and writes it to disk.
func run() error {
	moduleDir, err := lucideModuleDir()
	if err != nil {
		return err
	}

	names, err := loadIconNames(moduleDir)
	if err != nil {
		return err
	}

	source, err := generateCatalog(names)
	if err != nil {
		return err
	}

	if err := os.WriteFile(outputFile, source, 0o644); err != nil {
		return fmt.Errorf("write generated catalog: %w", err)
	}

	return nil
}

// lucideModuleDir locates the downloaded Lucide module source directory.
func lucideModuleDir() (string, error) {
	output, err := exec.Command(
		"go",
		"mod",
		"download",
		"-json",
		lucideModule,
	).Output()
	if err != nil {
		return "", fmt.Errorf("download Lucide module: %w", err)
	}

	var module moduleMetadata
	if err := json.Unmarshal(output, &module); err != nil {
		return "", fmt.Errorf("decode Lucide module metadata: %w", err)
	}
	if module.Error != "" {
		return "", fmt.Errorf("download Lucide module: %s", module.Error)
	}
	if module.Dir == "" {
		return "", errors.New("locate Lucide module: directory is empty")
	}

	return module.Dir, nil
}

// loadIconNames reads the icon names from a Lucide module directory.
func loadIconNames(moduleDir string) ([]string, error) {
	source, err := os.ReadFile(filepath.Join(moduleDir, lucideSource))
	if err != nil {
		return nil, fmt.Errorf("read Lucide catalog: %w", err)
	}

	names := extractIconNames(source)
	if len(names) == 0 {
		return nil, fmt.Errorf("no registered icons in Lucide catalog")
	}

	return names, nil
}

// extractIconNames extracts unique sorted icon names from Lucide source code.
func extractIconNames(source []byte) []string {
	matches := registration.FindAllSubmatch(source, -1)
	names := make([]string, len(matches))

	for index, match := range matches {
		names[index] = string(match[1])
	}

	slices.Sort(names)

	return slices.Compact(names)
}

// generateCatalog renders the generated Go source for the supplied icon names.
func generateCatalog(names []string) ([]byte, error) {
	var output bytes.Buffer

	output.WriteString(catalogHeader)

	for _, name := range names {
		fmt.Fprintf(
			&output,
			"\t{Name: %q, Label: %q, Source: %q},\n",
			name+"-lucide",
			label(name),
			"Lucide",
		)
	}

	output.WriteString("}\n")

	source, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated catalog: %w", err)
	}

	return source, nil
}

// label converts a kebab-case icon name to a display label.
func label(name string) string {
	words := strings.Split(name, "-")

	for index, word := range words {
		if word != "" {
			words[index] = strings.ToUpper(word[:1]) + word[1:]
		}
	}

	return strings.Join(words, " ")
}
