package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestExtractIconNames verifies extraction, sorting, and duplicate removal.
func TestExtractIconNames(t *testing.T) {
	t.Parallel()

	source := []byte(`
registerIcon("zap", data)
registerIcon("arrow-left", data)
registerIcon("zap", data)
`)

	names := extractIconNames(source)

	assert.Equal(t, []string{"arrow-left", "zap"}, names)
}

// TestExtractIconNamesWithoutRegistrations verifies an empty catalog remains empty.
func TestExtractIconNamesWithoutRegistrations(t *testing.T) {
	t.Parallel()

	assert.Empty(t, extractIconNames([]byte("package lucide")))
}

// TestLoadIconNames verifies catalog loading from a Lucide module directory.
func TestLoadIconNames(t *testing.T) {
	t.Parallel()

	moduleDir := t.TempDir()
	source := []byte(`
registerIcon("zap", data)
registerIcon("arrow-left", data)
`)

	require.NoError(t, os.WriteFile(filepath.Join(moduleDir, lucideSource), source, 0o600))

	names, err := loadIconNames(moduleDir)

	require.NoError(t, err)
	assert.Equal(t, []string{"arrow-left", "zap"}, names)
}

// TestLoadIconNamesRejectsEmptyCatalog verifies a Lucide source without registrations fails.
func TestLoadIconNamesRejectsEmptyCatalog(t *testing.T) {
	t.Parallel()

	moduleDir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(moduleDir, lucideSource), []byte("package lucide\n"), 0o600))

	_, err := loadIconNames(moduleDir)

	assert.EqualError(t, err, "no registered icons in Lucide catalog")
}

// TestGenerateCatalog verifies generated source uses names and display labels.
func TestGenerateCatalog(t *testing.T) {
	t.Parallel()

	source, err := generateCatalog([]string{"arrow-left", "zap"})

	require.NoError(t, err)
	assert.Equal(t, `// Code generated by go generate; DO NOT EDIT.

package icons

var lucideOptions = []Option{
	{Name: "arrow-left-lucide", Label: "Arrow Left", Source: "Lucide"},
	{Name: "zap-lucide", Label: "Zap", Source: "Lucide"},
}
`, string(source))
}

// TestLabel verifies kebab-case icon names become display labels.
func TestLabel(t *testing.T) {
	t.Parallel()

	t.Run("single word", func(t *testing.T) {
		t.Parallel()

		assert.Equal(t, "Zap", label("zap"))
	})

	t.Run("multiple words", func(t *testing.T) {
		t.Parallel()

		assert.Equal(t, "Arrow Left", label("arrow-left"))
	})

	t.Run("empty segment", func(t *testing.T) {
		t.Parallel()

		assert.Equal(t, "Arrow  Left", label("arrow--left"))
	})
}
