---
apiVersion: v1
kind: Service
metadata:
  name: kumbuka
spec:
  selector:
    app.kubernetes.io/name: kumbuka
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
