// Package route generates deployment-local browser URLs.
package route

import (
	"context"
	"net/http"

	"github.com/containeroo/httpprefix"
)

type contextKey struct{}

type deployment struct {
	prefix     string
	redirected bool
}

// redirectWriter also handles redirects generated by ServeMux and FileServer.
// Explicit application redirects are already generated by Redirect below.
type redirectWriter struct {
	http.ResponseWriter
	deployment *deployment
}

func (w *redirectWriter) Unwrap() http.ResponseWriter { return w.ResponseWriter }

func (w *redirectWriter) WriteHeader(status int) {
	if status >= 300 && status < 400 && !w.deployment.redirected {
		if target := w.Header().Get("Location"); target != "" {
			w.Header().Set("Location", httpprefix.RouteURL(w.deployment.prefix, target))
		}
	}
	w.ResponseWriter.WriteHeader(status)
}

// WithPrefix supplies the configured prefix to HTTP adapters after mounting.
func WithPrefix(handler http.Handler, prefix string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mount := &deployment{prefix: prefix}
		request := r.WithContext(context.WithValue(r.Context(), contextKey{}, mount))
		handler.ServeHTTP(&redirectWriter{ResponseWriter: w, deployment: mount}, request)
	})
}

// ForRequest generates a URL using the deployment prefix of a mounted request.
func ForRequest(r *http.Request, target string) string {
	mount, _ := r.Context().Value(contextKey{}).(*deployment)
	if mount == nil {
		return httpprefix.RouteURL("", target)
	}
	return httpprefix.RouteURL(mount.prefix, target)
}

// Redirect uses the same local URL rules as templates.
func Redirect(w http.ResponseWriter, r *http.Request, target string, status int) {
	if mount, ok := r.Context().Value(contextKey{}).(*deployment); ok {
		mount.redirected = true
	}
	http.Redirect(w, r, ForRequest(r, target), status)
}
