package main

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCheckFileReportsNestedAndEmbeddedFields(t *testing.T) {
	t.Parallel()

	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "input.go", `package example

// Item describes the result.
type Item struct {
	string

	// Value is the result value.
	Value string
}

func build() {
	var local struct {
		Number int
	}
	_ = local
}
`, parser.ParseComments)
	require.NoError(t, err)

	problems := checkFile(set, file)

	assert.Len(t, problems, 3)
}

func TestCheckFileAllowsExtendedFunctionDocumentation(t *testing.T) {
	t.Parallel()

	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "input.go", `package example

// Run starts the example.
// It performs additional initialization before returning.
func Run() {}
`, parser.ParseComments)
	require.NoError(t, err)

	problems := checkFile(set, file)

	assert.Empty(t, problems)
}

func TestCheckFileRequiresFunctionNameInSummary(t *testing.T) {
	t.Parallel()

	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "input.go", `package example

// Starts the example.
func Run() {}
`, parser.ParseComments)
	require.NoError(t, err)

	problems := checkFile(set, file)

	require.Len(t, problems, 1)
	assert.Contains(
		t,
		problems[0],
		"function Run GoDoc summary must begin with the function name",
	)
}

func TestCheckFileDoesNotAcceptLongerIdentifierPrefix(t *testing.T) {
	t.Parallel()

	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "input.go", `package example

// Runner starts the example.
func Run() {}
`, parser.ParseComments)
	require.NoError(t, err)

	problems := checkFile(set, file)

	require.Len(t, problems, 1)
	assert.Contains(
		t,
		problems[0],
		"function Run GoDoc summary must begin with the function name",
	)
}

func TestCheckTreeSkipsTestsGeneratedCodeAndDependencies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	files := map[string]string{
		"good.go":              "package example\n// Run starts the example.\nfunc Run() {}\n",
		"missing_test.go":      "package example\nfunc helper() {}\n",
		"generated.go":         "// Code generated by example. DO NOT EDIT.\npackage example\nfunc generated() {}\n",
		"vendor/dependency.go": "package dependency\nfunc missing() {}\n",
		"platform.go":          "//go:build windows\n\npackage example\n// Windows runs on Windows.\nfunc Windows() {}\n",
	}

	for name, source := range files {
		path := filepath.Join(root, name)

		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(source), 0o644))
	}

	problems, err := checkTree(root)

	require.NoError(t, err)
	assert.Empty(t, problems)
}
