package main

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"
)

func TestCheckFileReportsNestedAndEmbeddedFields(t *testing.T) {
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "input.go", `package example
// Item describes the result.
type Item struct {
 string
 // Value is the result value.
 Value string
}
func build() { var local struct { Number int }; _ = local }
`, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	problems := checkFile(set, file)
	if len(problems) != 3 {
		t.Fatalf("want 3 missing descriptions, got %v", problems)
	}
}

func TestCheckTreeSkipsTestsGeneratedCodeAndDependencies(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		"good.go":              "package example\n// Run starts the example.\nfunc Run() {}\n",
		"missing_test.go":      "package example\nfunc helper() {}\n",
		"generated.go":         "// Code generated by example. DO NOT EDIT.\npackage example\nfunc generated() {}\n",
		"vendor/dependency.go": "package dependency\nfunc missing() {}\n",
		"platform.go":          "//go:build windows\n\npackage example\n// Windows runs on Windows.\nfunc Windows() {}\n",
	}
	for name, source := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	problems, err := checkTree(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(problems) != 0 {
		t.Fatalf("unexpected missing descriptions: %v", problems)
	}
}
