package markdown

import (
	"bytes"
	"html"
	"strings"

	"github.com/kumbuka-me/kumbuka/pkg/plugin"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer"
	goldhtml "github.com/yuin/goldmark/renderer/html"
	"github.com/yuin/goldmark/text"
	"github.com/yuin/goldmark/util"
	xhtml "golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

// annotationRange records one rendered source range owned by a plugin inspector item.
type annotationRange struct {
	start, end int
	id         string
}

// resolvePluginReplacements restores opaque plugin substitutions without rescanning
// inserted values and records annotated byte ranges for the Goldmark pass.
func resolvePluginReplacements(source string, replacements []plugin.Replacement) (string, []annotationRange) {
	if len(replacements) == 0 {
		return source, nil
	}

	byToken := make(map[string]plugin.Replacement, len(replacements))
	for _, replacement := range replacements {
		if replacement.Token != "" {
			byToken[replacement.Token] = replacement
		}
	}
	if len(byToken) == 0 {
		return source, nil
	}

	var output strings.Builder
	var ranges []annotationRange
	position := 0
	for position < len(source) {
		start, token := nextReplacementToken(source, position, byToken)
		if start < 0 {
			output.WriteString(source[position:])
			break
		}
		replacement := byToken[token]
		output.WriteString(source[position:start])
		rangeStart := output.Len()
		output.WriteString(replacement.Value)
		if replacement.Annotation != "" && rangeStart < output.Len() {
			ranges = append(ranges, annotationRange{start: rangeStart, end: output.Len(), id: replacement.Annotation})
		}
		position = start + len(token)
	}

	return output.String(), ranges
}

// nextReplacementToken returns the earliest exact token starting at or after offset.
func nextReplacementToken(source string, offset int, replacements map[string]plugin.Replacement) (int, string) {
	best := -1
	bestToken := ""
	for token := range replacements {
		index := strings.Index(source[offset:], token)
		if index < 0 {
			continue
		}
		index += offset
		if best < 0 || index < best || (index == best && len(token) > len(bestToken)) {
			best = index
			bestToken = token
		}
	}
	return best, bestToken
}

var kindPluginAnnotation = ast.NewNodeKind("KumbukaPluginAnnotation")

// annotationNode marks text generated by one plugin-owned substitution.
type annotationNode struct {
	ast.BaseInline
	id string
}

// Kind returns the Goldmark node kind for plugin annotations.
func (n *annotationNode) Kind() ast.NodeKind { return kindPluginAnnotation }

// Dump writes a diagnostic representation of a plugin annotation node.
func (n *annotationNode) Dump(source []byte, level int) {
	ast.DumpHelper(n, source, level, map[string]string{"ID": n.id}, nil)
}

// annotationTransformer wraps only text segments originating from inspectable substitutions.
type annotationTransformer struct{ ranges []annotationRange }

// Transform adds annotation nodes while leaving image alt text and code spans to specialized rendering.
func (a annotationTransformer) Transform(document *ast.Document, _ text.Reader, _ parser.Context) {
	if len(a.ranges) == 0 {
		return
	}
	var nodes []*ast.Text
	_ = ast.Walk(document, func(node ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		switch node.Kind() {
		case ast.KindImage, ast.KindCodeSpan:
			return ast.WalkSkipChildren, nil
		}
		if textNode, ok := node.(*ast.Text); ok {
			nodes = append(nodes, textNode)
		}
		return ast.WalkContinue, nil
	})
	for _, node := range nodes {
		a.wrapText(node)
	}
}

// wrapText replaces annotated text ranges with annotation nodes.
func (a annotationTransformer) wrapText(node *ast.Text) {
	start, stop := node.Segment.Start, node.Segment.Stop
	if start == stop || node.Segment.Padding != 0 {
		return
	}
	parent := node.Parent()
	position := start
	changed := false
	appendText := func(from, to int, id string) {
		if from >= to {
			return
		}
		part := ast.NewTextSegment(text.NewSegment(from, to))
		part.SetRaw(node.IsRaw())
		if to == stop {
			part.SetSoftLineBreak(node.SoftLineBreak())
			part.SetHardLineBreak(node.HardLineBreak())
		}
		if id == "" {
			parent.InsertBefore(parent, node, part)
			return
		}
		span := &annotationNode{id: id}
		span.AppendChild(span, part)
		parent.InsertBefore(parent, node, span)
	}
	for _, region := range a.ranges {
		from, to := max(position, region.start), min(stop, region.end)
		if from >= to {
			continue
		}
		appendText(position, from, "")
		appendText(from, to, region.id)
		position = to
		changed = true
	}
	if !changed {
		return
	}
	appendText(position, stop, "")
	parent.RemoveChild(parent, node)
}

// annotationNodeRenderer renders generic plugin annotations without interpreting values as HTML.
type annotationNodeRenderer struct{ ranges []annotationRange }

// RegisterFuncs installs annotation-aware renderers with Goldmark.
func (a annotationNodeRenderer) RegisterFuncs(register renderer.NodeRendererFuncRegisterer) {
	register.Register(kindPluginAnnotation, a.renderAnnotation)
	if len(a.ranges) != 0 {
		register.Register(ast.KindCodeSpan, a.renderCodeSpan)
	}
}

// writeAnnotationStart writes the opening wrapper for one plugin annotation.
func writeAnnotationStart(w util.BufWriter, id string) {
	_, _ = w.WriteString(`<span class="plugin-annotation" data-plugin-annotation="` + html.EscapeString(id) + `">`)
}

// renderAnnotation writes the wrapper around a plugin annotation node.
func (a annotationNodeRenderer) renderAnnotation(w util.BufWriter, _ []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	if entering {
		writeAnnotationStart(w, node.(*annotationNode).id)
	} else {
		_, _ = w.WriteString("</span>")
	}
	return ast.WalkContinue, nil
}

// renderCodeSpan preserves Goldmark literal-code behavior while annotating exact source ranges.
func (a annotationNodeRenderer) renderCodeSpan(w util.BufWriter, source []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkContinue, nil
	}
	_, _ = w.WriteString("<code")
	goldhtml.RenderAttributes(w, node, goldhtml.CodeAttributeFilter)
	_, _ = w.WriteString(">")
	for child := node.FirstChild(); child != nil; child = child.NextSibling() {
		segment := child.(*ast.Text).Segment
		value := segment.Value(source)
		newline := bytes.HasSuffix(value, []byte("\n"))
		stop := segment.Stop
		if newline {
			stop--
		}
		position := segment.Start
		for _, region := range a.ranges {
			from, to := max(position, region.start), min(stop, region.end)
			if from >= to {
				continue
			}
			goldhtml.DefaultWriter.RawWrite(w, source[position:from])
			writeAnnotationStart(w, region.id)
			goldhtml.DefaultWriter.RawWrite(w, source[from:to])
			_, _ = w.WriteString("</span>")
			position = to
		}
		goldhtml.DefaultWriter.RawWrite(w, source[position:stop])
		if newline {
			_, _ = w.WriteString(" ")
		}
	}
	_, _ = w.WriteString("</code>")
	return ast.WalkSkipChildren, nil
}

// equivalentAnnotationHTML makes annotations fail closed when wrappers would alter document semantics.
func equivalentAnnotationHTML(annotated, normal string) bool {
	left, err := normalizedAnnotationHTML(annotated)
	if err != nil {
		return false
	}
	right, err := normalizedAnnotationHTML(normal)
	return err == nil && left == right
}

// normalizedAnnotationHTML removes generic plugin annotation wrappers before comparison.
func normalizedAnnotationHTML(value string) (string, error) {
	root := &xhtml.Node{Type: xhtml.ElementNode, Data: "div", DataAtom: atom.Div}
	nodes, err := xhtml.ParseFragment(strings.NewReader(value), root)
	if err != nil {
		return "", err
	}
	for _, node := range nodes {
		root.AppendChild(node)
	}
	var unwrap func(*xhtml.Node)
	unwrap = func(parent *xhtml.Node) {
		for node := parent.FirstChild; node != nil; {
			next := node.NextSibling
			unwrap(node)
			if node.Type == xhtml.ElementNode && node.Data == "span" && htmlAttribute(node, "class") == "plugin-annotation" && htmlAttribute(node, "data-plugin-annotation") != "" {
				for node.FirstChild != nil {
					child := node.FirstChild
					node.RemoveChild(child)
					parent.InsertBefore(child, node)
				}
				parent.RemoveChild(node)
			}
			node = next
		}
	}
	unwrap(root)
	var output strings.Builder
	for node := root.FirstChild; node != nil; node = node.NextSibling {
		if err := xhtml.Render(&output, node); err != nil {
			return "", err
		}
	}
	return output.String(), nil
}
