package markdown

import (
	"bytes"
	"html"
	"io"
	"slices"
	"strings"

	"github.com/kumbuka-me/kumbuka/pkg/plugin"
	"github.com/yuin/goldmark/v2/ast"
	"github.com/yuin/goldmark/v2/parser"
	"github.com/yuin/goldmark/v2/renderer"
	goldhtml "github.com/yuin/goldmark/v2/renderer/html"
	"github.com/yuin/goldmark/v2/text"
	"github.com/yuin/goldmark/v2/util"
	xhtml "golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

// annotationRange records one rendered source range owned by a plugin inspector item.
type annotationRange struct {
	// start and end store the corresponding values for annotation range.
	start, end int
	// id identifies annotation range.
	id string
}

// resolvePluginReplacements restores opaque plugin substitutions without rescanning
// inserted values and records annotated byte ranges for the Goldmark pass.
func resolvePluginReplacements(source string, replacements []plugin.Replacement) (string, []annotationRange) {
	if len(replacements) == 0 {
		return source, nil
	}

	byToken := make(map[string]plugin.Replacement, len(replacements))
	for _, replacement := range replacements {
		if replacement.Token != "" {
			byToken[replacement.Token] = replacement
		}
	}
	if len(byToken) == 0 {
		return source, nil
	}

	var output strings.Builder
	var ranges []annotationRange
	position := 0
	for position < len(source) {
		start, token := nextReplacementToken(source, position, byToken)
		if start < 0 {
			output.WriteString(source[position:])
			break
		}
		replacement := byToken[token]
		output.WriteString(source[position:start])
		rangeStart := output.Len()
		output.WriteString(replacement.Value)
		if replacement.Annotation != "" && rangeStart < output.Len() {
			ranges = append(ranges, annotationRange{start: rangeStart, end: output.Len(), id: replacement.Annotation})
		}
		position = start + len(token)
	}

	return output.String(), ranges
}

// nextReplacementToken returns the earliest exact token starting at or after offset.
func nextReplacementToken(source string, offset int, replacements map[string]plugin.Replacement) (int, string) {
	best := -1
	bestToken := ""
	for token := range replacements {
		index := strings.Index(source[offset:], token)
		if index < 0 {
			continue
		}
		index += offset
		if best < 0 || index < best || (index == best && len(token) > len(bestToken)) {
			best = index
			bestToken = token
		}
	}
	return best, bestToken
}

var kindPluginAnnotation = ast.NewNodeKind("KumbukaPluginAnnotation")

// annotationNode marks text generated by one plugin-owned substitution.
type annotationNode struct {
	// BaseInline embeds base inline behavior in annotation node.
	ast.BaseInline
	// id identifies annotation node.
	id string
}

// newAnnotationNode creates one initialized plugin annotation node.
func newAnnotationNode(id string) *annotationNode {
	node := &annotationNode{id: id}
	node.Init(node)
	return node
}

// Kind returns the Goldmark node kind for plugin annotations.
func (n *annotationNode) Kind() ast.NodeKind { return kindPluginAnnotation }

// Dump returns a diagnostic representation of a plugin annotation node.
func (n *annotationNode) Dump(_ []byte) *ast.NodeDump {
	return ast.NewNodeDump(n, map[string]any{"ID": n.id})
}

// annotationTransformer wraps only text segments originating from inspectable substitutions.
type annotationTransformer struct {
	// ranges contains the ranges associated with annotation transformer.
	ranges []annotationRange
}

// Transform adds annotation nodes while leaving image alt text and code spans to specialized rendering.
func (a annotationTransformer) Transform(document *ast.Document, reader text.Reader, _ parser.Context) {
	if len(a.ranges) == 0 {
		return
	}

	var nodes []*ast.Text
	_ = ast.Walk(document, func(node ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		switch node.Kind() {
		case ast.KindImage, ast.KindCodeSpan:
			return ast.WalkSkipChildren, nil
		}
		if textNode, ok := node.(*ast.Text); ok {
			nodes = append(nodes, textNode)
		}
		return ast.WalkContinue, nil
	})

	for _, node := range nodes {
		a.wrapText(node, reader.Decoder())
	}
}

// wrapText replaces annotated text ranges with annotation nodes.
func (a annotationTransformer) wrapText(node *ast.Text, decoder text.Decoder) {
	if node.Value.IsOwned() {
		return
	}
	index := node.Value.Index()
	start, stop := index.Start, index.Stop
	if start >= stop {
		return
	}

	parent := node.Parent()
	position := start
	changed := false
	appendText := func(from, to int, id string) {
		if from >= to {
			return
		}
		part := ast.NewText(text.NewSingleLineValueFromIndex(text.NewIndex(from, to), decoder))
		if to == stop {
			part.SetSoftLineBreak(node.SoftLineBreak())
			part.SetHardLineBreak(node.HardLineBreak())
		}
		if id == "" {
			parent.InsertBefore(node, part)
			return
		}
		span := newAnnotationNode(id)
		span.AppendChild(part)
		parent.InsertBefore(node, span)
	}

	for _, region := range a.ranges {
		from, to := max(position, region.start), min(stop, region.end)
		if from >= to {
			continue
		}
		appendText(position, from, "")
		appendText(from, to, region.id)
		position = to
		changed = true
	}
	if !changed {
		return
	}
	appendText(position, stop, "")
	parent.RemoveChild(node)
}

// annotationHTMLRendererExtension renders plugin annotation nodes and annotated code spans.
type annotationHTMLRendererExtension struct {
	// ranges contains the source ranges associated with plugin annotations.
	ranges []annotationRange
}

// RendererOptions registers annotation-aware HTML node renderers with Goldmark.
func (a annotationHTMLRendererExtension) RendererOptions(_ *goldhtml.Config) []goldhtml.Option {
	options := []goldhtml.Option{
		goldhtml.WithNodeRenderer(kindPluginAnnotation, goldhtml.NodeRendererFunc(a.renderAnnotation)),
	}
	if len(a.ranges) != 0 {
		options = append(options,
			goldhtml.WithNodeRenderer(ast.KindCodeSpan, goldhtml.NodeRendererFunc(a.renderCodeSpan)),
		)
	}
	return options
}

// writeAnnotationStart writes the opening wrapper for one plugin annotation.
func writeAnnotationStart(w util.BufWriter, id string) {
	_, _ = w.WriteString(`<span class="plugin-annotation" data-plugin-annotation="` + html.EscapeString(id) + `">`)
}

// renderAnnotation writes the wrapper around a plugin annotation node.
func (a annotationHTMLRendererExtension) renderAnnotation(
	writer io.Writer,
	_ []byte,
	node ast.Node,
	entering bool,
	_ renderer.Context,
) (ast.WalkStatus, error) {
	w := writer.(util.BufWriter)
	if entering {
		writeAnnotationStart(w, node.(*annotationNode).id)
	} else {
		_, _ = w.WriteString("</span>")
	}
	return ast.WalkContinue, nil
}

// renderCodeSpan preserves Goldmark literal-code behavior while annotating exact source ranges.
func (a annotationHTMLRendererExtension) renderCodeSpan(
	writer io.Writer,
	source []byte,
	node ast.Node,
	entering bool,
	renderContext renderer.Context,
) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkContinue, nil
	}

	w := writer.(util.BufWriter)
	span := node.(*ast.CodeSpan)
	_, _ = w.WriteString("<code")
	if node.Attributes() != nil {
		goldhtml.RenderAttributes(w, source, node, goldhtml.CodeAttributeFilter, renderContext)
	}
	_ = w.WriteByte('>')

	textWriter := goldhtml.ContextTextWriter(renderContext)
	for _, index := range normalizedCodeSpanIndices(span.Value, source) {
		a.writeAnnotatedCodeIndex(w, textWriter, source, index)
	}
	_, _ = w.WriteString("</code>")
	return ast.WalkSkipChildren, nil
}

// normalizedCodeSpanIndices mirrors Goldmark's CommonMark space trimming for code spans.
func normalizedCodeSpanIndices(value text.Value, source []byte) []text.Index {
	indices := slices.Clone(value.Indices())
	if len(indices) == 0 || !codeSpanShouldTrim(indices, source) {
		return indices
	}

	indices[0].Start++
	last := len(indices) - 1
	if indices[last].Stop > indices[last].Start {
		indices[last].Stop--
	}
	return indices
}

// codeSpanShouldTrim reports whether CommonMark removes one surrounding space from a code span.
func codeSpanShouldTrim(indices []text.Index, source []byte) bool {
	if len(indices) == 0 {
		return false
	}
	first := source[indices[0].Start:indices[0].Stop]
	lastIndex := indices[len(indices)-1]
	last := source[lastIndex.Start:lastIndex.Stop]
	if len(first) == 0 || len(last) == 0 {
		return false
	}

	hasNonBlank := false
	for _, index := range indices {
		if !util.IsBlank(source[index.Start:index.Stop]) {
			hasNonBlank = true
			break
		}
	}
	if !hasNonBlank {
		return false
	}
	return isCodeSpanSpace(first[0]) && isCodeSpanSpace(last[len(last)-1])
}

// isCodeSpanSpace reports whether a byte participates in CommonMark code-span edge trimming.
func isCodeSpanSpace(value byte) bool { return value == ' ' || value == '\n' }

// writeAnnotatedCodeIndex renders one raw code-span source index with annotation wrappers.
func (a annotationHTMLRendererExtension) writeAnnotatedCodeIndex(
	w util.BufWriter,
	textWriter util.BufWriter,
	source []byte,
	index text.Index,
) {
	position := index.Start
	for _, region := range a.ranges {
		from, to := max(position, region.start), min(index.Stop, region.end)
		if from >= to {
			continue
		}
		writeCodeSpanText(textWriter, source[position:from])
		writeAnnotationStart(w, region.id)
		writeCodeSpanText(textWriter, source[from:to])
		_, _ = w.WriteString("</span>")
		position = to
	}
	writeCodeSpanText(textWriter, source[position:index.Stop])
}

// writeCodeSpanText writes escaped code-span text while normalizing newlines to spaces.
func writeCodeSpanText(w util.BufWriter, value []byte) {
	_, _ = w.Write(bytes.ReplaceAll(value, []byte{'\n'}, []byte{' '}))
}

// equivalentAnnotationHTML makes annotations fail closed when wrappers would alter document semantics.
func equivalentAnnotationHTML(annotated, normal string) bool {
	left, err := normalizedAnnotationHTML(annotated)
	if err != nil {
		return false
	}
	right, err := normalizedAnnotationHTML(normal)
	return err == nil && left == right
}

// normalizedAnnotationHTML removes generic plugin annotation wrappers before comparison.
func normalizedAnnotationHTML(value string) (string, error) {
	root := &xhtml.Node{Type: xhtml.ElementNode, Data: "div", DataAtom: atom.Div}
	nodes, err := xhtml.ParseFragment(strings.NewReader(value), root)
	if err != nil {
		return "", err
	}
	for _, node := range nodes {
		root.AppendChild(node)
	}
	unwrapAnnotationElements(root)

	var output strings.Builder
	for node := root.FirstChild; node != nil; node = node.NextSibling {
		if err := xhtml.Render(&output, node); err != nil {
			return "", err
		}
	}
	return output.String(), nil
}

// unwrapAnnotationElements removes generic annotation spans while preserving their child nodes.
func unwrapAnnotationElements(parent *xhtml.Node) {
	for node := parent.FirstChild; node != nil; {
		next := node.NextSibling
		unwrapAnnotationElements(node)
		if isAnnotationElement(node) {
			unwrapElement(parent, node)
		}
		node = next
	}
}

// isAnnotationElement reports whether an HTML node is a generic plugin annotation wrapper.
func isAnnotationElement(node *xhtml.Node) bool {
	return node.Type == xhtml.ElementNode &&
		node.Data == "span" &&
		htmlAttribute(node, "class") == "plugin-annotation" &&
		htmlAttribute(node, "data-plugin-annotation") != ""
}

// unwrapElement replaces an element with its children in the original order.
func unwrapElement(parent, element *xhtml.Node) {
	for element.FirstChild != nil {
		child := element.FirstChild
		element.RemoveChild(child)
		parent.InsertBefore(child, element)
	}
	parent.RemoveChild(element)
}
