---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: kumbuka
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
