---
name: Autorelease
on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - closed

permissions:
  actions: write
  contents: write
  issues: write

concurrency:
  group: autorelease-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Create new tag
        uses: projectsyn/pr-label-tag-action@v1
        with:
          trigger: |
            Build
